---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: sample-app
  labels:
    app: sample-app  # This is the label applied to the Service metadata
spec:
  selector:
    app: prometheus-sample-app  # Changed from 'prometheus-sample-app' to 'sample-app' for consistency
  ports:
    - protocol: TCP
      name: scrapeport
      port: 8181
      targetPort: 8080
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app-servicemonitor
  namespace: sample-app
  labels:
    k8s-apps: sample-app  
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: sample-app  # Must match the label on the Service
  endpoints:
    - port: scrapeport   # Matches the port name in the Service
      path: /metrics
      interval: 30s
      scheme: http
